# generate_portfolio.py

"""Modular portfolio generator.
This script builds an HTML portfolio page based on structured data.
Sections are generated by helper functions to keep the logic clean.
"""

from datetime import datetime

# ------------------ user data ------------------
name = "Suraj Kumar Soni"
title = "Data Engineer"

email = "surajkr1000000@gmail.com"
phone = "+91-8210891342"
linkedin = "https://www.linkedin.com/in/suraj-soni-lkdin"
resume_file = "Suraj_Kumar_Soni_Data_Engineer.pdf"

about_intro = (
    "Results-driven Data Engineer with 4+ years of experience architecting high-performance data ecosystems. Expert in PySpark, SQL, and Azure Data Factory (ADF), with a focus on building cost-efficient ETL/ELT pipelines within the Databricks environment."
)

core_expertise = [
    "Performance Engineering: Eliminating data skewness and slow filters through Z-Order, Liquid Clustering, and Data Skipping techniques.",
    "Spark Mastery: Optimizing query execution via Adaptive Query Execution (AQE), Broadcast Joins, and Partition Tuning.",
    "Scalable Architecture: Designing Medallion Architectures and end-to-end orchestration for high-velocity, reliable data.",
]

finale_text = (
    "A self-motivated problem solver dedicated to squeezing every bit of performance out of Spark to deliver high-velocity, actionable intelligence."
)

about_text = about_intro  # kept for backward compatibility

expertise_points = [
    "Delta Lake Optimization",
    "Spark Performance Tuning",
    "Medallion Architecture",
    "Small File Handling",
    "CI/CD Automation",
    "SLA Monitoring",
]

skills = [
    "Python",
    "PySpark",
    "SQL",
    "DataBricks",
    "Azure Data Factory",
    "Azure Data Lake",
    "Delta Table",
]
skills = list(dict.fromkeys(skills))  # remove duplicates while preserving order

experience = [
    {
        "company": "Tredence Analytics ",
        "designation": "Senior Data Engineer",
        "dates": "28 Mar 2024 - Present",
        "details": """Led the end-to-end migration of Enterprise Master and Transactional Data from Teradata to Microsoft Azure, 
ensuring data integrity and alignment with Cloud Architecture best practices for high availability and 
performance.;
Engineered automated Azure Data Factory (ADF) ingestion and transformation pipelines for complex CPG 
data, utilizing Delta Lake and Medallion Architecture (Bronze, Silver, Gold) to provide curated, high
performance datasets.;
Developed a Python-based Automation Tool to programmatically convert Teradata DDL into Databricks
compatible notebooks, reducing manual development time by 60% and enforcing cross-team standardization.; 
Engineered a Modular Framework of reusable Python functions for common operations (e.g., Surrogate Key 
generation, Business Key hashing), significantly increasing code consistency and development efficiency.;
Optimized Databricks notebooks for high-performance processing by implementing Z-Ordering and Liquid 
Clustering to accelerate data skipping.;
Implemented Dynamic SCD Type 1, Type 2, and Fact Processing logic within Databricks, enhancing Data 
Accuracy and reducing operational overhead by 50%.;
Developed and Optimized PySpark notebooks in Databricks, implementing advanced Data Cleansing, 
Schema Validation, and Performance Tuning to transition data from Bronze to Silver layers for analytics
ready reporting.;
Spearheaded the data modeling phase by translating complex functional requirements into comprehensive 
Source-to-Target Mapping (STTM) documents for enterprise-scale datasets.""",
    },
    {
        "company": "R1RCM",
        "designation": "Data Engineer",
        "dates": "10 Nov 2023 - 27 Mar 2024",
        "details": """Collecting and standardizing patient data from healthcare facilities, categorizing accounts into bad debt, zero 
balance, or payment dues.;
Managing the end-to-end recovery process by analyzing and securing payments from insurance companies and 
patients.;
Orchestrating and monitoring intricate workflows using Airflow to ensure pipeline reliability.;
Optimizing Snowflake data warehousing for high-performance storage, retrieval, and advanced analytics.; 
Developing robust pipelines through expert-level Python programming and SQL script execution.; 
Leveraging PySpark for scalable big data processing and complex data analysis.""",
    },
    {
        "company": "Infosys Limited ",
        "designation": "Data Engineer",
        "dates": "17 Feb 2022 - 08 Nov 2023",
        "details": """Led data refinement projects to deliver precise sales insights through thorough statistical analysis (mean, 
median, mode) and rigorous data cleaning.;
Designed and implemented efficient ETL processes to extract, transform, and load data into Azure data 
warehouses.;
Demonstrated proficiency in SQL and Spark for querying and manipulating data within the data 
warehouse environment.;
Played a key role in the development and management of end-to-end data pipelines in Azure Data Factory, 
ensuring smooth data flow from source to destination.;
Applied industry best practices for data warehouse design, including dimensional modeling and schema 
optimization, to enhance storage and retrieval efficiency.""",
    },
    {
        "company": "Takhil Technologies",
        "designation": "Software Engineer",
        "dates": "01 Feb 2021 - 15 Feb 2022",
        "details": """Developed a user-friendly web interface using HTML, CSS, and JavaScript to serve as a Human-Machine 
Interface (HMI) connected to a PLC system.;
Cleaned and organized machine data using MySQL to display real-time information on a dashboard.""",
    },
    {
        "company": "Pratham Education Foundation",
        "designation": "Trainer",
        "dates": "01 Dec 2019 - 12 Nov 2020",
        "details": """Worked as Electrical Trainer and given training about Assistant Electrician (NSQF Level- 3) to 
underprivileged students.""",
    },
]

projects = [
    {
        "title": "Project One",
        "img": "https://via.placeholder.com/400x250",
        "description": "Quick description of project one.",
    },
    {
        "title": "Project Two",
        "img": "https://via.placeholder.com/400x250",
        "description": "Quick description of project two.",
    },
    {
        "title": "Project Three",
        "img": "https://via.placeholder.com/400x250",
        "description": "Quick description of project three.",
    },
]

leetcode_profile = "https://leetcode.com/u/surajkrsoni/"
hackerrank_profile = "https://www.hackerrank.com/profile/surajkrsoni"

# badge/certificate links (displayed in new section)
coding_profiles = [
    {
        "name": "HackerRank",
        "url": hackerrank_profile,
        # using placeholder image for now; replace with actual badge if available
        "img": "https://media.licdn.com/dms/image/v2/D560BAQE8MivsmbT7Ig/company-logo_200_200/company-logo_200_200/0/1705561459405/hackerrank_logo?e=2147483647&v=beta&t=7GKxD03RUnnvsxZkSgKmPcYUCe3YCw8R6OBjaC8j3E0",
    },
    {
        "name": "LeetCode",
        "url": leetcode_profile,
        "img": "https://cdn.iconscout.com/icon/free/png-256/free-leetcode-logo-icon-svg-download-png-2944960.png",
    },
]

# ------------------ HTML builders ------------------

def build_nav():
    items = [
        ("Home", "#home"),
        ("About", "#about"),
        ("Resume", resume_file),
        ("Contact", "#contact"),
        ("LinkedIn", linkedin),
    ]
    lis = []
    for label, href in items:
        target = ' target="_blank"' if href.startswith("http") or href == resume_file else ""
        lis.append(f'<li><a href="{href}"{target}>{label}</a></li>')
    links_html = "\n        ".join(lis)
    return f"""
<nav>
    <div class="nav-container">
        <a href="#home" class="logo">{name}</a>
        <span class="nav-toggle"><i class="fas fa-bars"></i></span>
        <ul>
        {links_html}
        </ul>
    </div>
</nav>
"""


def build_hero():
    subtitle = "Data Engineer specializing in scalable pipelines & insightful analytics."
    # single rotating text element; JS will update content
    return f"""
<section id="home" class="hero">
    <div class="hero-content">
        <h1>Hi, I'm {name}.</h1>
        <p>{subtitle}</p>
        <div class="looping-expertise">
            <span id="rotating-point"></span>
        </div>
        <a href="#about" class="btn btn-primary">About Me</a>
    </div>
</section>
"""


def build_about():
    expertise_items = "\n".join(f"                <li>{item}</li>" for item in core_expertise)
    return f"""
<section id="about" class="section container">
    <h2>About</h2>
    <p>{about_intro}</p>
    <h3>Core Expertise</h3>
    <ul>
{expertise_items}
    </ul>
    <p>{finale_text}</p>
</section>
"""


def build_skills():
    # single row of skill badges
    items = "\n".join(f"            <span class=\"skill-badge\">{s}</span>" for s in skills)
    return f"""
<section id="skills" class="section container skills-section">
    <h2>Skills</h2>
    <div class="skills-grid single-row">
{items}
    </div>
</section>
"""


def build_experience():
    cards = []
    for exp in experience:
        # render details as bullet list if it's a list
        details_val = exp.get('details','')
        if isinstance(details_val, list):
            detail_items = "\n".join(f"                        <li>{d}</li>" for d in details_val)
            details_html = f"<ul>\n{detail_items}\n                    </ul>"
        elif isinstance(details_val, str) and ";" in details_val:
            # split exclusively on semicolons; preserve other whitespace inside segments
            parts = [seg.strip() for seg in details_val.split(";") if seg.strip()]
            detail_items = "\n".join(f"                        <li>{d}</li>" for d in parts)
            details_html = f"<ul>\n{detail_items}\n                    </ul>"
        elif isinstance(details_val, str) and "\n" in details_val:
            # split multiline string into bullets (fallback)
            parts = [line.strip() for line in details_val.splitlines() if line.strip()]
            detail_items = "\n".join(f"                        <li>{d}</li>" for d in parts)
            details_html = f"<ul>\n{detail_items}\n                    </ul>"
        else:
            details_html = f"<p>{details_val}</p>"
        cards.append(
            f"""
                <div class='card'>
                    <h4>{exp['company']}</h4>
                    <div class='designation'>{exp['designation']}</div>
                    <div class='dates'>{exp['dates']}</div>
                    <div class='details'>{details_html}</div>
                </div>"""
        )
    return f"""
<section id="experience" class="section container">
    <h2>Experience</h2>
    <div class="cards">
{''.join(cards)}
    </div>
</section>
"""


def build_projects():
    cards = []
    for proj in projects:
        cards.append(
            """
                <div class="project-card">
                    <img src="{img}" alt="{title}">
                    <div class="project-info">
                        <h4>{title}</h4>
                        <p>{description}</p>
                    </div>
                </div>""".format(**proj)
        )
    return f"""
<section id="projects" class="section container projects">
    <h2>Featured Projects</h2>
    <div class="projects-grid">
{''.join(cards)}
    </div>
</section>
"""


def build_codingProfile():
    cards = []
    for cert in coding_profiles:
        cards.append(
            f"""
        <a href="{cert['url']}" target="_blank" class="cert-link">
            <img src="{cert['img']}" alt="{cert['name']} badge">
            <span>{cert['name']} Profile</span>
        </a>"""
        )
    return f"""
<section id="coding-achievements" class="section container certificates">
    <h2>Coding Achievements</h2>
    <div class="cert-grid">
{''.join(cards)}
    </div>
</section>
"""


def build_contact():
    return f"""
<section id="contact" class="section container">
    <h2>Contact</h2>
    <p><i class="fas fa-envelope"></i> Get in touch at <a href="mailto:{email}">{email}</a></p>
    <p><i class="fas fa-phone"></i> Call me at <a href="tel:+91-8210891342">+91-8210891342</a></p>
</section>
"""


def build_footer():
    year = datetime.now().year
    return f"""
<footer>
    <p>© {year} {name}. All Rights Reserved.</p>
</footer>
"""


def build_scripts():
    return """
<script>
    // toggle card expansion when anywhere on the card is clicked
    document.querySelectorAll('.card').forEach(card => {
        card.addEventListener('click', () => {
            card.classList.toggle('expanded');
        });
    });

    // mobile nav toggle
    const navToggle = document.querySelector('.nav-toggle');
    const navList = document.querySelector('nav ul');
    if (navToggle) {
        navToggle.addEventListener('click', () => {
            navList.classList.toggle('open');
        });
    }

    // smooth scroll for nav
    document.querySelectorAll('nav a[href^="#"]').forEach(link => {
        link.addEventListener('click', e => {
            e.preventDefault();
            document.querySelector(link.getAttribute('href')).scrollIntoView({ behavior: 'smooth' });
            if (navList.classList.contains('open')) navList.classList.remove('open');
        });
    });

    // rotating expertise points
    const points = [""" + ", ".join(f'\"{pt}\"' for pt in expertise_points) + """ ];
    let idx = 0;
    const el = document.getElementById('rotating-point');
    function showNext() {
        el.textContent = '';
        el.classList.remove('typewriter');
        void el.offsetWidth; // reflow
        el.textContent = points[idx];
        el.classList.add('typewriter');
        idx = (idx + 1) % points.length;
    }
    showNext();
    setInterval(showNext, 3000);

    // fade-in on scroll
    const sections = document.querySelectorAll('section');
    const observer = new IntersectionObserver((entries) => {
        entries.forEach(entry => {
            if (entry.isIntersecting) {
                entry.target.classList.add('in-view');
                observer.unobserve(entry.target);
            }
        });
    }, { threshold: 0.1 });
    sections.forEach(sec => observer.observe(sec));
</script>
"""
def generate_html():
    # assemble pieces using f-strings so that variables are interpolated immediately
    html_parts = []
    html_parts.append(f"""<!DOCTYPE html>
<html>
<head>
    <meta charset=\"UTF-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
    <title>{name} - Portfolio</title>
    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;700&family=Roboto:wght@300;400;500&display=swap\" rel=\"stylesheet\">
    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">
    <link rel=\"stylesheet\" href=\"style.css\">
</head>
<body>""" )
    html_parts.append(build_nav())
    html_parts.append(build_hero())
    html_parts.append("<main>")
    html_parts.append(build_about())
    html_parts.append(build_skills())
    html_parts.append(build_experience())
    # html_parts.append(build_projects())
    html_parts.append(build_codingProfile())
    html_parts.append(build_contact())
    html_parts.append("</main>")
    html_parts.append(build_footer())
    html_parts.append(build_scripts())
    return "\n".join(html_parts)


if __name__ == "__main__":
    html = generate_html()
    with open(r"C:\Suraj\portfolio\index.html", "w", encoding="utf-8") as f:
        f.write(html)
    print("portfolio generated successfully!")